# Homework 1: Data Reading & Manipulation

In this homework, you will practice:
1. Reading data from CSV files and APIs
2. Data manipulation techniques covered in Week 2

# Section 1: Reading Data

## 1.1 Reading CSV Files

##### IMPORTANT: We will read data from the `data/hw/` folder so you need to remember to go back two folders to access data

In [1]:
#IMPORT PANDAS TOOLS
import pandas as pd
import os

In [2]:
os.getcwd()

'/Users/jocarver/Documents/GitHub/datascience-publicpolicy-2026/notebooks/hw'

### 1.1.1 GDP and Democracy Data

Load the `democracy_gdp.csv` file.

In [33]:
democracy_gdp_filepath = '../../data/hw/democracy_gdp.csv'
democracy_gdp = pd.read_csv(democracy_gdp_filepath)
democracy_gdp.head(4)

,country,year,v2x_frassoc_thick,NGDPDPC,NGDP_RPCH,v2x_pubcorr,v2xnp_regcorr,v2xel_frefair,v2x_freexp,v2elembcap
0,AFG,1990,0.063,NaN,NaN,0.556,0.538,0.069,0.085,-1.65
1,AFG,1991,0.068,NaN,NaN,0.556,0.538,0.069,0.074,-1.65
2,AFG,1992,0.134,NaN,NaN,0.645,0.736,0.028,0.071,-1.65
3,AFG,1993,0.159,NaN,NaN,0.843,0.909,0.000,0.069,-1.65

### 1.1.2 Green house gas (GHG) Emissions Data

Load the `ghg.csv` file.

In [7]:
ghg_file_path = '../../data/hw/ghg.csv'
ghg = pd.read_csv(ghg_file_path)
ghg.tail(5)

            Country  year     emissions
11443  GLOBAL TOTAL  2019  51278.347920
11444  GLOBAL TOTAL  2020  49327.538885
11445  GLOBAL TOTAL  2021  51568.250032
11446  GLOBAL TOTAL  2022  51968.471601
11447  GLOBAL TOTAL  2023  52962.900859

## 1.2 Reading Data from an API

YOU MUST RUN THE NEXT CELL TO DOWNLOAD GDP AND POPULATION DATA

In [8]:
import requests
import io

def download_worldbank(indicator, countries, date_start, date_end):
    url_base = 'https://api.worldbank.org/v2/'
    country_codes = ';'.join(countries)
    url = f'{url_base}country/{country_codes}/indicator/{indicator}?date={date_start}:{date_end}&per_page=30000'
    response = requests.get(url)
    df = pd.read_xml(io.BytesIO(response.content))
    return df

### 1.2.1 Download GDP Data (1990-2026)

Download GDP per capita data for a different set of countries than those in the CSV files.

In [11]:
gdp_data = download_worldbank(
    indicator='NY.GDP.PCAP.CD',
    date_start= 1990,
    date_end= 2026,
    countries= [
        'BRB',
        'BLR',
        'BEL',
        'BLZ',
        'BEN',
        'BMU',
        'BTN',
        'BOL',
        'BIH',
        'BWA'
    ]
)
gdp_data.head(2)
gdp_data.country.unique()

array(['Belgium', 'Benin', 'Bosnia and Herzegovina', 'Belarus', 'Belize',
       'Bermuda', 'Bolivia', 'Barbados', 'Bhutan', 'Botswana'],
      dtype=object)

### 1.2.2 Download Population Data (1990-2026)

Download population data for the same countries.

In [12]:
population_indicator = 'SP.POP.TOTL'



country_list = [
    "USA",  # United States of America
    "CAN",  # Canada
    "MEX",  # Mexico
    "GBR",  # United Kingdom of Great Britain and Northern Ireland
    "FRA",  # France
    "DEU",  # Germany (Deutschland)
    "JPN",  # Japan
    "AUS"   # Australia
]

pop_data = download_worldbank(
    indicator=population_indicator,
    countries=country_list,
    date_start=1990,
    date_end=2026
)
pop_data.tail(3)

,indicator,country,countryiso3code,date,value,unit,obs_status,decimal
285,"Population, total",United States,USA,1992,256514000.0,NaN,NaN,0
286,"Population, total",United States,USA,1991,252981000.0,NaN,NaN,0
287,"Population, total",United States,USA,1990,249623000.0,NaN,NaN,0

# Section 2: Data Manipulation

Now let's practice the data manipulation techniques from Week 2.

## 2.1 Select Columns

Select specific columns from the democracy_gdp dataset.

In [22]:
democracy_gdp.describe()

,year,v2x_frassoc_thick,NGDPDPC,NGDP_RPCH,v2x_pubcorr,v2xnp_regcorr,v2xel_frefair,v2x_freexp,v2elembcap
count,5600.000000,5600.000000,4515.000000,4515.000000,5589.000000,5589.000000,5600.000000,5600.000000,5600.000000
mean,2007.000000,0.764491,20259.020440,4.690474,0.237886,0.317942,0.772290,0.783635,1.909207
std,10.100407,0.200621,8781.215967,3.055591,0.224371,0.230505,0.252077,0.219095,0.910033
min,1990.000000,0.021000,3557.753750,-4.900000,0.004000,0.008000,0.000000,0.011000,-3.141000
25%,1998.000000,0.779000,13066.128000,2.900000,0.109000,0.108000,0.755000,0.754000,1.848000
50%,2007.000000,0.839000,18053.591000,4.600000,0.157000,0.276000,0.878000,0.881000,2.155000
75%,2016.000000,0.857000,26600.549000,6.700000,0.209000,0.361000,0.939000,0.921000,2.535000
max,2024.000000,0.933000,37518.466000,11.600000,0.966000,0.960000,0.961000,0.956000,2.731000

In [16]:
democracy_gdp.country[0:5]

0    AFG
1    AFG
2    AFG
3    AFG
4    AFG
Name: country, dtype: object

In [23]:
democracy_gdp[['country', 'year','NGDPDPC']]

     country  year  NGDPDPC
0        AFG  1990      NaN
1        AFG  1991      NaN
2        AFG  1992      NaN
3        AFG  1993      NaN
4        AFG  1994      NaN
...      ...   ...      ...
5595     VNM  2020      NaN
5596     VNM  2021      NaN
5597     VNM  2022      NaN
5598     VNM  2023      NaN
5599     VNM  2024      NaN

[5600 rows x 3 columns]

## 2.2 Filter Rows

Filter rows based on conditions.

In [24]:
# Show unique values in a column
democracy_gdp.country.unique()

array(['AFG', 'ARM', 'AZE', 'Asia (avg)', 'BGD', 'BTN', 'CHN', 'GEO',
       'HKG', 'IDN', 'IND', 'JPN', 'KAZ', 'KGZ', 'KHM', 'KOR', 'LAO',
       'LKA', 'MDV', 'MMR', 'MNG', 'MYS', 'NPL', 'PAK', 'PHL', 'PRK',
       'SGP', 'THA', 'TJK', 'TKM', 'TLS', 'TWN', 'UZB', 'VNM'],
      dtype=object)

In [32]:
# Filter using query

democracy_gdp.query("country == 'JPN' and year in [1990, 1991, 1992]")

,country,year,v2x_frassoc_thick,NGDPDPC,NGDP_RPCH,v2x_pubcorr,v2xnp_regcorr,v2xel_frefair,v2x_freexp,v2elembcap
385,JPN,1990,0.905,NaN,NaN,0.048,0.108,0.921,0.934,1.809
386,JPN,1991,0.904,NaN,NaN,0.048,0.108,0.921,0.934,1.809
387,JPN,1992,0.904,NaN,NaN,0.048,0.108,0.921,0.934,1.809

## 2.3 Multiple Conditions

Filter using multiple conditions.

In [34]:
# Filter with multiple conditions

democracy_gdp.query("country == 'KOR' and year == 2024")

,country,year,v2x_frassoc_thick,NGDPDPC,NGDP_RPCH,v2x_pubcorr,v2xnp_regcorr,v2xel_frefair,v2x_freexp,v2elembcap
2701,KOR,2024,0.817,36128.987,2.0,0.167,0.094,0.932,0.756,2.535
2702,KOR,2024,0.817,36128.987,2.0,0.167,0.094,0.932,0.756,2.535
2703,KOR,2024,0.817,36128.987,2.0,0.167,0.094,0.932,0.756,2.535
2704,KOR,2024,0.817,36128.987,2.0,0.167,0.094,0.932,0.756,2.535
2705,KOR,2024,0.817,36128.987,2.0,0.167,0.094,0.932,0.756,2.535
...,...,...,...,...,...,...,...,...,...,...
2760,KOR,2024,0.817,36128.987,2.0,0.167,0.094,0.932,0.756,2.535
2761,KOR,2024,0.817,36128.987,2.0,0.167,0.094,0.932,0.756,2.535
2762,KOR,2024,0.817,36128.987,2.0,0.167,0.094,0.932,0.756,2.535
2763,KOR,2024,0.817,36128.987,2.0,0.167,0.094,0.932,0.756,2.535
2764,KOR,2024,0.817,36128.987,2.0,0.167,0.094,0.932,0.756,2.535

## 2.4 Filter in a List

Filter rows where column value is in a list.

In [39]:
# Filter Multiple and show unique countries
# You can either do one or two lines

democracy_gdp.query('country in ["JPN", "KOR"]')['country'].unique()

array(['JPN', 'KOR'], dtype=object)

## 2.5 Select Rows and Columns

Combine row filtering with column selection.

In [36]:
# Filter rows and select columns

democracy_gdp.query('country == "JPN" and year in [2022, 2023, 2024]')[['country', 'year', 'NGDPDPC', 'v2x_pubcorr']]

    country  year  NGDPDPC  v2x_pubcorr
417     JPN  2022      NaN        0.037
418     JPN  2023      NaN        0.037
419     JPN  2024      NaN        0.037

## 2.6 Rename Columns

Rename columns in the dataframe.

In [ ]:
# Before rename
democracy_gdp.head(2)

,country,year,v2x_frassoc_thick,NGDPDPC,NGDP_RPCH,v2x_pubcorr,v2xnp_regcorr,v2xel_frefair,v2x_freexp,v2elembcap
0,AFG,1990,0.063,NaN,NaN,0.556,0.538,0.069,0.085,-1.65
1,AFG,1991,0.068,NaN,NaN,0.556,0.538,0.069,0.074,-1.65

In [37]:
# Rename using rename with axis parameter

democracy_gdp.rename({'year': 'date'}, axis = 1).head(2)

,country,date,v2x_frassoc_thick,NGDPDPC,NGDP_RPCH,v2x_pubcorr,v2xnp_regcorr,v2xel_frefair,v2x_freexp,v2elembcap
0,AFG,1990,0.063,NaN,NaN,0.556,0.538,0.069,0.085,-1.65
1,AFG,1991,0.068,NaN,NaN,0.556,0.538,0.069,0.074,-1.65